name: email-sort-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - openai
      - beautifulsoup4
      - lxml
      - black
      - marimo
      - jupyterlab
      - notebook
      - ipykernel
      - python-dotenv
      - numpy
      - pandas
      - matplotlib
      - seaborn
